WebApplication1/Models/testimonial.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class testimonial
    {
        public int Test_ID { get; set; }
        [Display(Name = "Customer Testimonial")]
        public string Cust_Test { get; set; }
        [Display(Name = "Customer Name")]
        public Nullable<int> Cust_Name { get; set; }

        public virtual Customer Customer { get; set; }
    }
}

WebApplication1/Controllers/testimonialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class testimonialsController : Controller
    {
        private Vehicle_Insurance_ManagmentEntities db = new Vehicle_Insurance_ManagmentEntities();

        // GET: testimonials
        public ActionResult Testimonial()
        {
            var testimonials = db.testimonials.Include(t => t.Customer);
            return View(testimonials.ToList());
        }

        // GET: testimonials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            testimonial testimonial = db.testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // GET: testimonials/Create
        public ActionResult Create()
        {
            ViewBag.Cust_Name = new SelectList(db.Customers, "Cust_Id", "Cust_Name");
            return View();
        }

        // POST: testimonials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Test_ID,Cust_Test,Cust_Name")] testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.testimonials.Add(testimonial);
                db.SaveChanges();
                return RedirectToAction("Testimonial");
            }

            ViewBag.Cust_Name = new SelectList(db.Customers, "Cust_Id", "Cust_Name", testimonial.Cust_Name);
            return View(testimonial);
        }

        // GET: testimonials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            testimonial testimonial = db.testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cust_Name = new SelectList(db.Customers, "Cust_Id", "Cust_Name", testimonial.Cust_Name);
            return View(testimonial);
        }

        // POST: testimonials/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Test_ID,Cust_Test,Cust_Name")] testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testimonial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Testimonial");
            }
            ViewBag.Cust_Name = new SelectList(db.Customers, "Cust_Id", "Cust_Name", testimonial.Cust_Name);
            return View(testimonial);
        }

        // GET: testimonials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            testimonial testimonial = db.testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // POST: testimonials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            testimonial testimonial = db.testimonials.Find(id);
            db.testimonials.Remove(testimonial);
            db.SaveChanges();
            return RedirectToAction("Testimonial");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/testimonials/Create.cshtml
@model WebApplication1.Models.testimonial

@{
    ViewBag.Title = "Create";
}
<div style="margin-top: 110px">
<h2 style="text-align:center">Your message</h2>

@using (Html.BeginForm("Create", "testimonials"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="text-align:center">testimonial</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cust_Test, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cust_Test, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cust_Test, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cust_Name, "Cust_Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cust_Name", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cust_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Testimonials","Account")
</div>
</div>

WebApplication1/Views/testimonials/Delete.cshtml
@model WebApplication1.Models.testimonial

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>testimonial</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cust_Test)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cust_Test)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.Cust_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Cust_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/testimonials/Details.cshtml
@model WebApplication1.Models.testimonial

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>testimonial</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cust_Test)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cust_Test)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.Cust_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Cust_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Test_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/testimonials/Edit.cshtml
@model WebApplication1.Models.testimonial

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>testimonial</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Test_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Cust_Test, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cust_Test, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cust_Test, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cust_Name, "Cust_Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cust_Name", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cust_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default btn-danger" />
            </div>
        </div>
    </div>
}
@if (Session["Admin"]!=null)
{ 
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
}

WebApplication1/Views/testimonials/Testimonial.cshtml
@model IEnumerable<WebApplication1.Models.testimonial>

@{
    ViewBag.Title = "Testimonials";
}
<div style="margin-top:100px">
    <h2 style="text-align:center">Testimonials</h2>

    <p style="text-align:center">
        @Html.ActionLink("Add your Testimonial", "Create", "testimonials")
    </p>
    <section class="w3l-clients" id="clients">
        <!-- /grids -->
        <div class="cusrtomer-layout py-5">
            <div class="container py-lg-5 py-md-4">
                <!-- /grids -->
                <div class="row testimonial-row">
                    <div class="col-lg-4 heading align-self">
                        <h6 class="title-small">Client Testimonials</h6>
                        <h3 class="title-big mb-md-5 mb-4">What our customers are saying</h3>
                    </div><div id="owl-demo1" class="col-lg-8 owl-two owl-carousel owl-theme mb-md-3 mb-sm-5 mb-4" >
    @foreach (var item in Model)
    {
        <div class="item" style="height:350px;width:350px;">
            <div class="testimonial-content">
                <div class="testimonial">
                    <blockquote>
                        <q>
                            @Html.DisplayFor(modelItem => item.Cust_Test)
                        </q>
                    </blockquote>
                    <div class="testi-des">
                        <div class="test-img">
                            <img src="~/assets/images/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper.png" class="img-fluid" alt="client-img">
                        </div>
                        <div class="peopl align-self">

                            <h3>@Html.DisplayFor(modelItem => item.Customer.Cust_Name)</h3>
                            <p class="indentity">@Html.DisplayFor(model => item.Customer.Cust_Email) </p>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Test_ID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Test_ID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Test_ID })
                        </div>
                    </div>
                </div>
            </div>
        </div>


    }
</div>

                </div>
            </div>
        </div>
    </section>
</div>