WebApplication1/Controllers/ClaimsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ClaimsController : Controller
    {
        private Vehicle_Insurance_ManagmentEntities db = new Vehicle_Insurance_ManagmentEntities();

        // GET: Claims
        public ActionResult Claim()
        {
            var claims = db.Claims.Include(c => c.Billing);
            return View(claims.ToList());
        }
        public ActionResult ClaimByCustomer(int? id)
        {
            List<Claim> claim = db.Claims.Where(x => x.Bill_Id == id).ToList();
            return View("Claim", claim);
        }
        // GET: Claims/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Claim claim = db.Claims.Find(id);
            if (claim == null)
            {
                return HttpNotFound();
            }
            return View(claim);
        }

        // GET: Claims/Create
        public ActionResult Create()
        {
            ViewBag.Bill_Id = new SelectList(db.Billings, "Bill_Id", "Bill_Date");
            return View();
        }

        // POST: Claims/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Claim_Id,Bill_Id,Claim_Date,Accident_Place,Accident_Description,Claim_Amount")] Claim claim)
        {
            if (ModelState.IsValid)
            {
                claim.Bill_Id = Convert.ToInt32(Session["UserID"]);
                db.Claims.Add(claim);
                db.SaveChanges();
                return RedirectToAction("ClaimByCustomer", new { id = Convert.ToInt32(Session["UserID"]) });
                
            }

            ViewBag.Bill_Id = new SelectList(db.Billings, "Bill_Id", "Bill_Date", claim.Bill_Id);
            return View(claim);
        }

        // GET: Claims/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Claim claim = db.Claims.Find(id);
            if (claim == null)
            {
                return HttpNotFound();
            }
            ViewBag.Bill_Id = new SelectList(db.Billings, "Bill_Id", "Bill_Date", claim.Bill_Id);
            return View(claim);
        }

        // POST: Claims/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Claim_Id,Bill_Id,Claim_Date,Accident_Place,Accident_Description,Claim_Amount")] Claim claim)
        {
            if (ModelState.IsValid)
            {
                db.Entry(claim).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Claim");
            }
            ViewBag.Bill_Id = new SelectList(db.Billings, "Bill_Id", "Bill_Date", claim.Bill_Id);
            return View(claim);
        }

        // GET: Claims/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Claim claim = db.Claims.Find(id);
            if (claim == null)
            {
                return HttpNotFound();
            }
            return View(claim);
        }

        // POST: Claims/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Claim claim = db.Claims.Find(id);
            db.Claims.Remove(claim);
            db.SaveChanges();
            return RedirectToAction("Claim");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/Company_ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class Company_ExpenseController : Controller
    {
        private Vehicle_Insurance_ManagmentEntities db = new Vehicle_Insurance_ManagmentEntities();

        // GET: Company_Expense
        public ActionResult CompanyExp()
        {
            return View(db.Company_Expense.ToList());
        }

        // GET: Company_Expense/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company_Expense company_Expense = db.Company_Expense.Find(id);
            if (company_Expense == null)
            {
                return HttpNotFound();
            }
            return View(company_Expense);
        }

        // GET: Company_Expense/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Company_Expense/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Exp_Id,Exp_Description,Exp_Amt,Exp_Date")] Company_Expense company_Expense)
        {
            if (ModelState.IsValid)
            {
                db.Company_Expense.Add(company_Expense);
                db.SaveChanges();
                return RedirectToAction("CompanyExp");
            }

            return View(company_Expense);
        }

        // GET: Company_Expense/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company_Expense company_Expense = db.Company_Expense.Find(id);
            if (company_Expense == null)
            {
                return HttpNotFound();
            }
            return View(company_Expense);
        }

        // POST: Company_Expense/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Exp_Id,Exp_Description,Exp_Amt,Exp_Date")] Company_Expense company_Expense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company_Expense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CompanyExp");
            }
            return View(company_Expense);
        }

        // GET: Company_Expense/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company_Expense company_Expense = db.Company_Expense.Find(id);
            if (company_Expense == null)
            {
                return HttpNotFound();
            }
            return View(company_Expense);
        }

        // POST: Company_Expense/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company_Expense company_Expense = db.Company_Expense.Find(id);
            db.Company_Expense.Remove(company_Expense);
            db.SaveChanges();
            return RedirectToAction("CompanyExp");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;


namespace WebApplication1.Controllers
{
    public class CustomersController : Controller
    {
        private Vehicle_Insurance_ManagmentEntities db = new Vehicle_Insurance_ManagmentEntities();

        // GET: Customers
        public ActionResult Customer()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Cust_Id,Cust_Name,Cust_Add,Cust_Phone,Cust_Email,Cust_Pass,Cust_CNIC")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Customer");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Cust_Id,Cust_Name,Cust_Add,Cust_Phone,Cust_Email,Cust_Pass,Cust_CNIC")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Customer");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Customer");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PurchasesController : Controller
    {
        private Vehicle_Insurance_ManagmentEntities db = new Vehicle_Insurance_ManagmentEntities();

        // GET: Purchases
        public ActionResult Purchase()
        {
            var purchases = db.Purchases.Include(p => p.Pur_Date).Include(p => p.Vehicle);
            return View(purchases.ToList());
        }
        public ActionResult PurchaseByCustomer(int? id)
        {
            List<Purchase> Purchase = db.Purchases.Where(x => x.Pur_Pol == id).ToList();
            return View("Purchase", Purchase);
        }

        // GET: Purchases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        // GET: Purchases/Create
        public ActionResult Create()
        {
            ViewBag.Pur_Pol = new SelectList(db.InsurancePolicies, "Pol_Id", "PolicyName");
            ViewBag.Vehicle = new SelectList(db.Vehicles, "Veh_Id", "Veh_Name");
            return View();
        }

        // POST: Purchases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Pur_Id,Vehicle,Pur_Pol,Pur_Date,Total_Amt,PP_Status")] Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                purchase.Pur_Pol = Convert.ToInt32(Session["UserID"]);
                db.Purchases.Add(purchase);
                db.SaveChanges();
                return RedirectToAction("PurchaseByCustomer", new { id = Convert.ToInt32(Session["UserID"]) });
            }

            ViewBag.Pur_Pol = new SelectList(db.InsurancePolicies, "Pol_Id", "PolicyName", purchase.Pur_Pol);
            ViewBag.Vehicle = new SelectList(db.Vehicles, "Veh_Id", "Veh_Name", purchase.Vehicle);
            return View(purchase);
        }

        // GET: Purchases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            ViewBag.Pur_Pol = new SelectList(db.InsurancePolicies, "Pol_Id", "PolicyName", purchase.Pur_Pol);
            ViewBag.Vehicle = new SelectList(db.Vehicles, "Veh_Id", "Veh_Name", purchase.Vehicle);
            return View(purchase);
        }

        // POST: Purchases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Pur_Id,Vehicle,Pur_Pol,Pur_Date,Total_Amt,PP_Status")] Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchase).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Purchase");
            }
            ViewBag.Pur_Pol = new SelectList(db.InsurancePolicies, "Pol_Id", "PolicyName", purchase.Pur_Pol);
            ViewBag.Vehicle = new SelectList(db.Vehicles, "Veh_Id", "Veh_Name", purchase.Vehicle);
            return View(purchase);
        }

        // GET: Purchases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Purchase purchase = db.Purchases.Find(id);
            db.Purchases.Remove(purchase);
            db.SaveChanges();
            return RedirectToAction("Purchase");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Admin/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
}

<h2>AboutUs</h2>

</header>
<!-- //header -->
<section class="w3l-about-breadcrumb">
    <div class="breadcrumb-bg breadcrumb-bg-about py-5">
        <div class="container py-lg-5 py-md-3">
            <h2 class="title">About Us</h2>
        </div>
    </div>
</section>
<section class="w3l-breadcrumb">
    <div class="container">
        <ul class="breadcrumbs-custom-path">
            <li><a href="#url">Home</a></li>
            <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> About Us</li>
        </ul>
    </div>
</section>
<section class="w3l-about py-5" id="about">
    <div class="container py-lg-5 py-md-3">
        <div class="about-block">
            <h6 class="title-small">About company</h6>
            <h3 class="title-big">We are qualified & of experience in this field.</h3>
            <p class="mt-md-4 mt-3">
                Lorem ipsum viverra feugiat. Pellen tesque libero ut justo,
                ultrices in ligula. Semper at tempufddfel. Lorem ipsum dolor sit amet
                elit. Non quae, fugiat nihil ad. Lorem ipsum dolor sit amet. Lorem ipsum init
                dolor sit, amet elit. Dolor ipsum non velit, culpa!
            </p>
            <a href="#url" class="img-height">
                <img src="~/assets/images/Customer Value.jpg" alt="" class="radius-image img-fluid mt-md-5 mt-4">
            </a>
        </div>
    </div>
    </div>
</section>
@{ Html.RenderAction("Services_Data");}
<!-- about block3 -->
<section class="w3l-content-4 py-5" id="features">
    <div class="content-4-main py-lg-5 py-md-4">
        <div class="container">
            <div class="content-info-in row">
                <div class="content-left col-lg-6">
                    <h3 class="title-small"> What we do</h3>
                    <h3 class="title-big">Our auto shop technicians are dedicated to helping you get back on the road.</h3>
                    <p class="mt-4">
                        Phasellus lacinia id erat eu
                        ullamcorper. Nunc id ipsum fringilla, gravida felis vitae. Phasellus lacinia id, sunt in
                        culpa quis.
                    </p>
                    <p class="mt-3">
                        Phasellus lacinia. Lorem ipsum dolor, sit amet consectetur init adipisicing elit. Eos,
                        debitis. Quas minima sunt natus tempore, maiores aliquid modi gravida felis vitae.
                    </p>
                    <img src="~/assets/images/banner3.jpg" class="img-fluid mt-3" alt="">
                </div>
                <div class="content-right col-lg-6 pl-lg-4 mt-lg-0 mt-md-5 mt-3">
                    <div class="row content4-right-grids mb-lg-5 mb-4">
                        <div class="col-2 content4-right-icon">
                            <div class="content4-icon">
                                <span class="fa fa-cogs"></span>
                            </div>
                        </div>
                        <div class="col-10 content4-right-info">
                            <h6><a href="#url">Free diagnostics.</a></h6>
                            <p>
                                Lorem ipsum dolor sit amet,Ea consequuntur illum facere aperiam sequi optio
                                consectetur
                                adipisicing.
                            </p>
                        </div>
                    </div>
                    <div class="row content4-right-grids mb-lg-5 mb-4">
                        <div class="col-2 content4-right-icon">
                            <div class="content4-icon">
                                <span class="fa fa-wrench"></span>
                            </div>
                        </div>
                        <div class="col-10 content4-right-info">
                            <h6><a href="#url"> Fast repair.</a></h6>
                            <p>
                                Lorem ipsum dolor sit amet,Ea consequuntur illum facere aperiam sequi optio
                                consectetur
                                adipisicing.
                            </p>
                        </div>
                    </div>
                    <div class="row content4-right-grids">
                        <div class="col-2 content4-right-icon">
                            <div class="content4-icon">
                                <span class="fa fa-clock-o"></span>
                            </div>
                        </div>
                        <div class="col-10 content4-right-info">
                            <h6><a href="#url"> 90 days warranty</a></h6>
                            <p>
                                Lorem ipsum dolor sit amet,Ea consequuntur illum facere aperiam sequi optio
                                consectetur
                                adipisicing.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- //about block3 -->
<section class="w3l-about4 py-5">
    <div class="container px-0 py-lg-5 py-md-4">
        <div class="history-info position-relative">
            <div class="heading ml-auto">
                <h3 class="title-big">We’ll make your car feel brand new visit our workshop today.</h3>
                <p class="mt-3">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit sunt in culpa qui officia
                    sed deserunt mollit anim id est laborum mollit anim id est nulla.
                </p>
                <a href="#small-dialog" class="popup-with-zoom-anim play-view text-center mt-4">
                    <span class="video-play-icon">
                        <span class="fa fa-play"></span>
                    </span>
                </a>
            </div>
            <div class="position-relative">
                <!-- dialog itself, mfp-hide class is required to make dialog hidden -->
                <div id="small-dialog" class="zoom-anim-dialog mfp-hide">
                    <iframe src="https://player.vimeo.com/video/169036704" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
                </div>
                <!-- popup -->
                <div id="popup-video" class="pop-overlay">
                    <div class="popup">
                        <div class="align-popup-video">
                            <iframe src="https://www.youtube.com/embed/JemJbNJ4ZtU" frameborder="0"
                                    allowfullscreen></iframe>
                            <a class="close" href="#portfolio">&times;</a>
                        </div>
                    </div>
                </div>
                <!-- /popup -->
            </div>
        </div>
    </div>
</section>
<!--/team-sec-->
@{ Html.RenderAction("Team_Data");
}
<!--//team-sec-->

WebApplication1/Views/Admin/Claim.cshtml
@model IEnumerable<WebApplication1.Models.Claim>

@{
    ViewBag.Title = "Claim";
}
<div style="margin-top:100px">
    <h2 style="text-align:center">Claim</h2>

    <p style="text-align:center">
        @Html.ActionLink("Create New", "Create", "Claim")
    </p>
    <div class="container-fluid">
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Claim_Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Accident_Place)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Accident_Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Claim_Amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Billing.Bill_Date)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Claim_Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Accident_Place)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Accident_Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Claim_Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Billing.Bill_Date)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Claims", new { id = item.Claim_Id }, null) |
                        @Html.ActionLink("Details", "Details", "Claims", new { id = item.Claim_Id }, null) |
                        @Html.ActionLink("Delete", "Delete", "Claims", new { id = item.Claim_Id }, null)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

WebApplication1/Views/Admin/Comp_Exp.cshtml
@model IEnumerable<WebApplication1.Models.Company_Expense>

@{
    ViewBag.Title = "Comp_Exp";
}
<div style="margin-top:100px">
    <h2 style="text-align:center">Comp_Exp</h2>

    <p style="text-align:center">
        @Html.ActionLink("Create New", "Create", "Company_Expense")
    </p>
    <div class="container-fluid">
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Exp_Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Exp_Amt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Exp_Date)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Exp_Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Exp_Amt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Exp_Date)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Company_Expense", new { id = item.Exp_Id }, null) |
                        @Html.ActionLink("Details", "Details", "Company_Expense", new { id = item.Exp_Id }, null) |
                        @Html.ActionLink("Delete", "Delete", "Company_Expense", new { id = item.Exp_Id }, null)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

WebApplication1/Views/Admin/Delete.cshtml
@model WebApplication1.Models.Company_Admin

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company_Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Admin_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Admin/Purchase.cshtml
@model IEnumerable<WebApplication1.Models.Purchase>

@{
    ViewBag.Title = "Purchase";
}
<div style="margin-top:100px">
    <h2 style="text-align:center">Purchase</h2>

    <p style="text-align:center">
        @Html.ActionLink("Create New", "Create", "Purchases")
    </p>
    <div class="">
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pur_Pol)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pur_Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total_Amt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PP_Status)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vehicle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pur_Pol)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pur_Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Total_Amt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PP_Status)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Purchases", new { id = item.Pur_Id }, null) |
                        @Html.ActionLink("Details", "Details", "Purchases", new { id = item.Pur_Id}, null) |
                        @Html.ActionLink("Delete", "Delete", "Purchases", new { id = item.Pur_Id}, null)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>